theme: jekyll-theme-minimal
title: [/assets/needlecast-new-icon-sm.png]
site:
  logo: /assets/needlecast-new-icon-sm.png
  description: Needlecast Validators, run by Envoy Labs
  github:
    repository_url: https://github.com/envoylabs/