theme: jekyll-theme-minimal
title: [Needlecast Validators Blog]
site:
  logo: https://raw.githubusercontent.com/envoylabs/blog/gh-pages/assets/needlecast-new-icon-sm.png
  description: Needlecast Validators, run by Envoy Labs
  github:
    repository_url: https://github.com/envoylabs/